name: application-YAML
server:
  port: ${PORT:8080}
  debug: true

logging.level:
  com.sap : INFO
  org.springframework: INFO
  org.springframework.security: INFO
  org.springframework.web: INFO

spring:
  http.converters.preferred-json-mapper: gson

server.error.include-message: always